# Generated by Django 5.0.2 on 2025-06-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_category_recipe_image_recipe_prep_time_recipe_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(blank=True, help_text='Время готовки в минутах', null=True),
        ),
    ]
