# Generated by Django 5.0.2 on 2025-06-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'recipe'], name='accounts_li_user_id_278835_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['created_at'], name='accounts_li_created_75fe21_idx'),
        ),
    ]
